version: '3.5'

services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  db:
    image: mysql:5.7
    container_name: sekolah_db_project
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswordsekolah
      MYSQL_DATABASE: sekolah
      MYSQL_USER: admin_sekolah
      MYSQL_PASSWORD: admin_sekolah.password
      TZ: Asia/Jakarta
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./sekolah_backup.sql:/docker-entrypoint-initdb.d/sekolah_backup.sql  # Ini untuk load data awal
volumes:
  mysql_data: